(() => {
 const photographs=[['the-invitation','The Invitation'],['dhol-comes-first','Dhol Comes First'],['the-turn','The Turn'],['the-step','The Step'],['the-circle','The Circle'],['the-center','The Center'],['aajrakh','Aajrakh'],['blurr','Blurr'],['rny00498','The Ground'],['installation-1','Under the lights'],['installation-2','The illuminated entrance'],['installation-3','Bamboo and tradition'],['installation-4','The fabric installation']];
 const photoPath=file=>'assets/'+file+(file.startsWith('installation-')?'.jpg':'.webp');
 const track=document.querySelector('#gallery-track'),lightbox=document.querySelector('#lightbox');let photoIndex=0;
 const isPaused=()=>document.documentElement.classList.contains('motion-paused')||matchMedia('(prefers-reduced-motion: reduce)').matches;
 const motion=()=>isPaused()?'instant':'smooth';
 photographs.forEach(([file,title],i)=>{const button=document.createElement('button');button.className='gallery-card';button.setAttribute('aria-label','View '+title);button.innerHTML=`<div class="photo"><img src="${photoPath(file)}" alt="${title} — Divi Garba" loading="lazy" width="900" height="1200"></div><div class="caption"><span>${String(i+1).padStart(2,'0')}</span><h3>${title}</h3></div>`;button.addEventListener('click',()=>{const open=()=>{showPhoto(i);lightbox.showModal()};const card=button.querySelector('img'),target=document.querySelector('#light-img');if(!document.startViewTransition||isPaused()){open();return}card.style.viewTransitionName='divi-photo';document.startViewTransition(()=>{card.style.viewTransitionName='';open();target.style.viewTransitionName='divi-photo'}).finished.finally(()=>{target.style.viewTransitionName=''})});track.append(button)});
 function showPhoto(i){photoIndex=(i+photographs.length)%photographs.length;const[file,title]=photographs[photoIndex];document.querySelector('#light-img').src=photoPath(file);document.querySelector('#light-img').alt=title+' — Divi Garba';document.querySelector('#light-caption').textContent=`${String(photoIndex+1).padStart(2,'0')} / ${photographs.length} · ${title}`}
 document.querySelector('.light-prev').onclick=()=>showPhoto(photoIndex-1);document.querySelector('.light-next').onclick=()=>showPhoto(photoIndex+1);
 lightbox.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'){e.preventDefault();showPhoto(photoIndex-1)}if(e.key==='ArrowRight'){e.preventDefault();showPhoto(photoIndex+1)}if(e.key==='Home'){e.preventDefault();showPhoto(0)}if(e.key==='End'){e.preventDefault();showPhoto(photographs.length-1)}});
 let touchStart=null;const lightImage=document.querySelector('#light-img');
 lightImage.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')touchStart={x:e.clientX,y:e.clientY}});
 lightImage.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.4)showPhoto(photoIndex+(dx<0?1:-1));touchStart=null});lightImage.addEventListener('pointercancel',()=>touchStart=null);
 function galleryStep(direction){const card=track.querySelector('.gallery-card');const gap=parseFloat(getComputedStyle(track).gap)||0;track.scrollBy({left:direction*(card.getBoundingClientRect().width+gap),behavior:motion()})}
 document.querySelector('#gallery-prev').onclick=()=>galleryStep(-1);document.querySelector('#gallery-next').onclick=()=>galleryStep(1);
 function updateGalleryControls(){const max=track.scrollWidth-track.clientWidth;document.querySelector('#gallery-prev').disabled=track.scrollLeft<3;document.querySelector('#gallery-next').disabled=track.scrollLeft>=max-3}
 track.addEventListener('scroll',updateGalleryControls,{passive:true});new ResizeObserver(updateGalleryControls).observe(track);updateGalleryControls();
 track.addEventListener('keydown',e=>{const cards=[...track.querySelectorAll('.gallery-card')],index=cards.indexOf(document.activeElement);if(index<0)return;let target=index;if(e.key==='ArrowRight')target=Math.min(cards.length-1,index+1);else if(e.key==='ArrowLeft')target=Math.max(0,index-1);else if(e.key==='Home')target=0;else if(e.key==='End')target=cards.length-1;else return;e.preventDefault();cards[target].focus({preventScroll:true});cards[target].scrollIntoView({behavior:motion(),block:'nearest',inline:'nearest'})});
 const navTargets=[['.hero','#home'],['#experience','#experience'],['#ritual','#ritual'],['#gallery','#gallery'],['#plan','#plan']].map(([selector,hash])=>({element:document.querySelector(selector),hash}));
 let navFrame=0;function updateNav(){navFrame=0;const range=document.documentElement.scrollHeight-innerHeight;document.querySelector('.reading-progress').style.transform='scaleX('+(range>0?Math.min(1,Math.max(0,scrollY/range)):0)+')';let current='#home';for(const item of navTargets){if(item.element.getBoundingClientRect().top<=innerHeight*.4)current=item.hash}document.querySelectorAll('nav a').forEach(a=>{const active=a.hash===current;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}
 window.addEventListener('scroll',()=>{if(!navFrame)navFrame=requestAnimationFrame(updateNav)},{passive:true});window.addEventListener('resize',updateNav);updateNav();
 const reduced=matchMedia('(prefers-reduced-motion: reduce)'),fine=matchMedia('(hover: hover) and (pointer: fine)'),resets=[];
 document.querySelectorAll('.hero-visual,.story-image,.gallery-card .photo,.feature-image').forEach(surface=>{let rect=null,frame=0;const reset=()=>{cancelAnimationFrame(frame);rect=null;surface.style.transform='';surface.classList.remove('depth-active')};resets.push(reset);const glint=document.createElement('span');glint.className='depth-glint';glint.setAttribute('aria-hidden','true');surface.append(glint);
 surface.addEventListener('pointerenter',()=>{if(!isPaused()&&fine.matches)rect=surface.getBoundingClientRect()});
 surface.addEventListener('pointermove',e=>{if(isPaused()||!fine.matches)return;rect??=surface.getBoundingClientRect();const x=Math.max(-.5,Math.min(.5,(e.clientX-rect.left)/rect.width-.5)),y=Math.max(-.5,Math.min(.5,(e.clientY-rect.top)/rect.height-.5));cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{surface.classList.add('depth-active');surface.style.transform=`perspective(1200px) rotateX(${-y*5}deg) rotateY(${x*7}deg)`;surface.style.setProperty('--shine-x',`${(x+.5)*100}%`);surface.style.setProperty('--shine-y',`${(y+.5)*100}%`)})});
 surface.addEventListener('pointerleave',reset);surface.addEventListener('pointercancel',reset)});
 const resetAll=()=>resets.forEach(reset=>reset());window.addEventListener('resize',resetAll);window.addEventListener('scroll',resetAll,{passive:true});window.addEventListener('divi:motion',resetAll);reduced.addEventListener('change',resetAll);fine.addEventListener('change',resetAll);
})();
