import {eventDays,parseNights,buildShareUrl,buildCalendar} from './planner-core.js';
const selected=new Set(parseNights(new URL(location.href).searchParams.get('nights')));
const options=document.querySelector('#night-options'),summary=document.querySelector('#night-summary'),calendar=document.querySelector('#calendar-download'),share=document.querySelector('#share-plan'),status=document.querySelector('#plan-status'),selectAll=document.querySelector('#select-all-nights');
const weekday=new Intl.DateTimeFormat('en',{weekday:'short',timeZone:'Asia/Kolkata'});
const names=window.DIVI_CONFIG?.nightNames||{};
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
eventDays.forEach(day=>{const name=names[day],button=document.createElement('button');button.className='night-option';button.setAttribute('aria-label',`${day} October 2026${name?` · ${name.en}`:''}`);button.innerHTML=`<span>${weekday.format(new Date(`2026-10-${day}T20:00:00+05:30`))}</span><strong>${day}</strong><span>Oct</span>${name?`<em class="night-name"><b lang="gu">${escape(name.gu)}</b>${escape(name.en)}</em>`:''}`;button.dataset.day=day;button.onclick=()=>{selected.has(day)?selected.delete(day):selected.add(day);update()};options.append(button)});
const sorted=()=>[...selected].sort((a,b)=>a-b);
const describe=days=>days.map(day=>names[day]?`${day} Oct · ${names[day].en}`:`${day} Oct`).join(', ');
function update(){options.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(selected.has(Number(b.dataset.day)))));calendar.disabled=selected.size===0;summary.textContent=selected.size?`${describe(sorted())} · ${selected.size} ${selected.size===1?'night':'nights'} selected`:'Choose a night to plan with your friends.';share.textContent=selected.size?'Share these nights':'Share event';selectAll.textContent=selected.size===10?'Clear selection':'Select all ten';status.textContent=''}
selectAll.onclick=()=>{if(selected.size===10)selected.clear();else eventDays.forEach(d=>selected.add(d));update()};
calendar.onclick=()=>{if(!selected.size)return;const url=URL.createObjectURL(new Blob([buildCalendar(sorted())],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Divi-Garba-2026.ics';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);status.textContent='Calendar file downloaded. Open it to add your selected nights.'};
share.onclick=async()=>{const url=buildShareUrl(location.href,sorted());const text=`Divi Garba · ${selected.size?describe(sorted()):'11–20 October'} 2026\nFrom 8:00 PM IST · Master Farm, B/s Sardardham, Vaishnodevi Circle\nA valid event pass is required.`;try{if(navigator.share){await navigator.share({title:'Divi Garba 2026',text,url});status.textContent='Share options opened.'}else{await navigator.clipboard.writeText(text+'\n'+url);status.textContent='Your selected nights and link are copied. Share them with your circle.'}}catch(error){if(error.name==='AbortError')return;status.textContent='Copy this link to share your plan: ';const link=document.createElement('a');link.href=url;link.textContent=url;status.append(link)}};
const start=new Date('2026-10-11T20:00:00+05:30').getTime(),lastEntry=new Date('2026-10-21T02:00:00+05:30').getTime(),label=document.querySelector('#countdown-label'),values=document.querySelector('#countdown-values');
const heroCountdown=document.querySelector('.hero-countdown');
function countdown(){const now=Date.now(),remaining=start-now;if(remaining<=0){label.textContent=now<=lastEntry?'Divi Garba · 11–20 October':'The 2026 dates have passed';values.textContent=now<=lastEntry?'From 8:00 PM IST':'';if(heroCountdown){heroCountdown.textContent=now<=lastEntry?'The circle is open tonight':'';heroCountdown.hidden=now>lastEntry;}return}const mins=Math.floor(remaining/60000);
 if(heroCountdown){const days=Math.floor(mins/1440);heroCountdown.textContent=days>0?`${days} ${days===1?'day':'days'} to the first beat`:`${Math.floor(mins/60)}h ${mins%60}m to the first beat`;heroCountdown.hidden=false;}
 const parts=[['Days',Math.floor(mins/1440)],['Hours',Math.floor(mins%1440/60)],['Minutes',mins%60]];values.replaceChildren(...parts.map(([name,value])=>{const part=document.createElement('span'),number=document.createElement('strong');number.textContent=String(value).padStart(2,'0');part.append(number,document.createTextNode(name));return part}))}
update();countdown();setInterval(()=>{if(!document.hidden)countdown()},30000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)countdown()});
if(selected.size)document.querySelector('.planner-drawer').open=true;
const mobile=document.querySelector('.mobile-booking');new IntersectionObserver(entries=>mobile.classList.toggle('visible',!entries[0].isIntersecting),{threshold:0}).observe(document.querySelector('.hero'));
